services:
  yarp:
    image: simpleproxy:1.1.1
    build: .
    volumes:
      - ./appSettings.json:/app/appSettings.json:ro
      - ./certificate/keys:/app/keys:ro
    restart: 'unless-stopped'
    network_mode: host
